spring.application.name=flowb2b-backend

# ===============================
# MYSQL
# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/flowb2b_db?useSSL=false&serverTimezone=America/Lima}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=${SERVER_PORT:8080}

# ===============================
# JWT
# ===============================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=3600000